version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test-backend:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install backend dependencies
          command: cd backend && npm install
      - run:
          name: Install JUnit coverage reporter
          command: npm install -D jest-junit
      - run:
          name: Run backend tests
          command: npm run test:backend
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
workflows:
  test:
    jobs:
      - test-backend
