version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test-backend:
    executor:
      name: node/default
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - node/install-packages
      - run:
          command: npm run test:backend
workflows:
  build-and-test:
    jobs:
      - test-backend
