version: 2.1

orbs:
  node: circleci/node@3.0.0
  cypress: cypress-io/cypress@1

jobs:
  test-backend-mock:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install backend dependencies
          command: cd backend && npm install
      - run:
          name: Install JUnit coverage reporter
          command: npm install -D jest-junit
      - run:
          name: Run backend mock tests
          command: npm run test:backend:mock:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./backend/reports/junit/
      - store_artifacts:
          path: ./backend/reports/junit
  test-frontend:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install frontend dependencies
          command: cd frontend && npm install
      - run:
          name: Install JUnit coverage reporter
          command: npm install -D jest-junit
      - run:
          name: Run frontend unit tests
          command: npm run test:frontend:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./frontend/reports/junit/
      - store_artifacts:
          path: ./frontend/reports/junit
  test-frontend-e2e:
  executor:
    name: node/default
  steps:
    - cypress/install:
        build: npm run build
    - cypress/run:
        start: npm start

workflows:
  test:
    jobs:
      - test-backend-mock
      - test-frontend
      - cypress/install:
          build: npm run build
      - cypress/run:
          requires:
            - cypress/install
          working_directory: frontend
          start: npm start
