version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test-backend:
    machine: true
    steps:
      - checkout
      - run:
          command: cd backend && npm install
      - run:
          command: npm run test:backend
workflows:
  test:
    jobs:
      - test-backend
